### ISSUE TITLE
Running scripts no longer works

### ISSUE THREAD

**Issue by Moelf** [simonschoelly/KittyTerminalImages.jl#10]
I can't see the second plot.

**Comment by simonschoelly** [comment]
Hi, can you provide more information, so that I can reproduce the bug? For example what version of Julia & this package are you using, and what are the commands that you used to plot?

**Comment by Moelf** [comment]
Julia 1.6.1, Plots 1.15.2, KittyTerminalImages 0.2.0. The script is the one in README and run via `julia script.jl`

**Comment by Moelf** [comment]
I'm happy to report that with KittyTerminalImages 0.3.0 the issue is gone, but I wonder if we can update the compact packages versions ranges a bit since that originally caused 0.2.0 to be installed.

**Comment by simonschoelly** [comment]
I guess the version problem was with ImageCore.jl? Apparently CompatHelper that should have notified me of the new version was disabled, so I never realized that.

I have now updated the version of the ImageCore dependeny to 0.9 and also created a new patch release so that should be fixed.

Thanks for notifying me :)
